# Generated by Django 4.1.5 on 2023-02-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
