# Generated by Django 4.1.5 on 2023-03-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
