# Generated by Django 4.1.5 on 2023-03-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='online',
        ),
    ]
