# Generated by Django 4.1.5 on 2023-01-29 15:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transmission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ManyToManyField(related_name='peers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
