# Generated by Django 4.1.5 on 2023-03-15 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_online'),
        ('transmission', '0002_alter_transmission_bytes_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='online', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
