# Generated by Django 4.1.5 on 2023-03-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transmission', '0003_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='online',
            old_name='users',
            new_name='user',
        ),
    ]
