# Generated by Django 4.1.5 on 2023-03-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmission', '0006_alter_transmission_file_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
