# Generated by Django 4.1.5 on 2023-03-17 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transmission', '0007_transmission_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Peer',
        ),
    ]
