# Generated by Django 4.1.5 on 2023-03-17 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transmission', '0008_alter_history_id_alter_transmission_id_delete_peer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transmission.transmission')),
                ('reciever', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_recieving', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_sending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
