# Generated by Django 4.1.5 on 2023-03-23 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transmission', '0010_remove_history_enddate_remove_history_startdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transmission',
            old_name='filename',
            new_name='file_name',
        ),
    ]
