name: Test code against written django testcases

on:
  workflow_call:
  workflow_dispatch:

  push:
    branches: 
      - '**'
  
  pull_request:
    branches:
      - '**'

jobs:
  Django-Test:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{secrets.SECRET_KEY}}
    
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Update Pip
        run: |
          pip install --upgrade pip
      
      - name: Install Dependecies
        run:  |
          pip install -r requirements.txt
      
      - name: Run Test Cases
        run:  |
          python manage.py test